name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.2.0
        env:
          GITHUB_TOKEN: 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
          USERNAME: thuan2172001
      - name: Commit & Push
        run: |
          git config user.name thuan2172001
          git config user.email thuan2172001@gmail.com
          git add -A .
          git commit -m "generated"
          git push
